### ISSUE TITLE
Failed to run improver vulnerabilities.importers.nginx.NginxBasicImprover.

### ISSUE THREAD

**Issue by wiredhikari** [nexB/vulnerablecode#1143]
On running
 ``` docker-compose exec vulnerablecode ./manage.py improve --all ```
 Output: 
```                                                                
Improving data using vulnerabilities.improvers.default.DefaultImprover
Successfully improved data using vulnerabilities.improvers.default.DefaultImprover
Improving data using vulnerabilities.importers.nginx.NginxBasicImprover
Cannot call GitHub API without a token set in the GH_TOKEN environment variable.
Traceback (most recent call last):
  File "/app/vulnerabilities/management/commands/improve.py", line 59, in improve_data
    ImproveRunner(improver).run()
  File "/app/vulnerabilities/improve_runner.py", line 47, in run
    process_inferences(
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/vulnerabilities/improve_runner.py", line 71, in process_inferences
    for inference in inferences:
  File "/app/vulnerabilities/importers/nginx.py", line 239, in get_inferences
    all_versions = list(self.fetch_nginx_version_from_git_tags())
  File "/app/vulnerabilities/importers/nginx.py", line 294, in fetch_nginx_version_from_git_tags
    for version in nginx_versions:
  File "/app/vulnerabilities/package_managers.py", line 469, in fetch
    for node in self.fetch_tag_nodes(pkg):
  File "/app/vulnerabilities/package_managers.py", line 518, in fetch_tag_nodes
    response = utils.fetch_github_graphql_query(graphql_query)
  File "/app/vulnerabilities/utils.py", line 243, in fetch_github_graphql_query
    raise GitHubTokenError(msg)
vulnerabilities.utils.GitHubTokenError: Cannot call GitHub API without a token set in the GH_TOKEN environment variable.
Failed to run improver vulnerabilities.importers.nginx.NginxBasicImprover. Continuing...
Improving data using vulnerabilities.importers.github.GitHubBasicImprover
Successfully improved data using vulnerabilities.importers.github.GitHubBasicImprover
Improving data using vulnerabilities.importers.debian.DebianBasicImprover
Successfully improved data using vulnerabilities.importers.debian.DebianBasicImprover
Improving data using vulnerabilities.importers.gitlab.GitLabBasicImprover
Successfully improved data using vulnerabilities.importers.gitlab.GitLabBasicImprover
Improving data using vulnerabilities.importers.istio.IstioImprover
Successfully improved data using vulnerabilities.importers.istio.IstioImprover
Improving data using vulnerabilities.improvers.oval.DebianOvalBasicImprover
Successfully improved data using vulnerabilities.improvers.oval.DebianOvalBasicImprover
Improving data using vulnerabilities.improvers.oval.UbuntuOvalBasicImprover
Successfully improved data using vulnerabilities.improvers.oval.UbuntuOvalBasicImprover
Improving data using vulnerabilities.importers.apache_httpd.ApacheHTTPDImprover
Successfully improved data using vulnerabilities.importers.apache_httpd.ApacheHTTPDImprover
CommandError: 1 failed!: vulnerabilities.importers.nginx.NginxBasicImprover

```

**Comment by TG1999** [comment]
@wiredhikari do you have a valid github token added in your env variables ?
