### ISSUE TITLE
Encoding issue in  `vulnerabilities.importers.fireeye.FireyeImporter`

### ISSUE THREAD

**Issue by harsh098** [nexB/vulnerablecode#1403]
I was receiving this small error on running the importer `vulnerabilities.importers.fireeye.FireyeImporter` 
turns out this was caused by wrong encoding type. 

## Error
```
Importing data using vulnerabilities.importers.fireeye.FireyeImporter
        Fetching Advisories █████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙ 17%
Traceback (most recent call last):
  File "/home/harsh/vulnerablecode/vulnerabilities/management/commands/import.py", line 64, in import_data
    ImportRunner(importer).run()
  File "/home/harsh/vulnerablecode/vulnerabilities/import_runner.py", line 61, in run
    count = self.process_advisories(advisory_datas=advisory_datas, importer_name=importer_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harsh/vulnerablecode/vulnerabilities/import_runner.py", line 95, in process_advisories
    for data in advisory_datas:
  File "/home/harsh/vulnerablecode/vulnerabilities/importers/fireeye.py", line 57, in advisory_data
    yield parse_advisory_data(raw_data=f.read(), file=file, base_path=base_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harsh/vulnerablecode/vulnerabilities/importers/fireeye.py", line 79, in parse_advisory_data
    md_dict = md_list_to_dict(md_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harsh/vulnerablecode/vulnerabilities/importers/fireeye.py", line 153, in md_list_to_dict
    md_dict[md_key].append(md_line)
    ~~~~~~~^^^^^^^^
KeyError: ''
Failed to run importer vulnerabilities.importers.fireeye.FireyeImporter. Continuing...
Fetching Data from Databases |████████████████████████████████| 1/1
CommandError: 1 failed!: vulnerabilities.importers.fireeye.FireyeImporter

```  
---
# How to reproduce 
```
./manage.py import  vulnerabilities.importers.fireeye.FireyeImporter
```

I am making a change and making a PR here

**Comment by harsh098** [comment]
The following PR fixes this please have a look
#1404
