### ISSUE TITLE
Slow migration process, very busy disk activity

### ISSUE THREAD

**Issue by uboznikov** [nexB/vulnerablecode#357]
I deleted then re-created images after pulling latest.

Then re-run data migration, it is very slow and hogs disk activity, and it's only the first source (NVD) . Also slows down the other apps.

![image](https://user-images.githubusercontent.com/16329085/108170669-66fd1700-7135-11eb-9449-5f9258ea8634.png)

I recall that this was not the case before.

**Comment by chess-equality** [comment]
After about 5 hours it hasn't gone past importing the first item which is NVD. Disk still very busy. I killed it then got this:

![image](https://user-images.githubusercontent.com/29477940/108220767-0dffa400-7172-11eb-92de-381142d9a3cd.png)

Is this a bug?

**Comment by uboznikov** [comment]
About 5 hours it hasn't gone past the first item which is NVD. Disk still very busy. I killed it then got this:

![image](https://user-images.githubusercontent.com/16329085/108221267-8ebea000-7172-11eb-91f2-7191414cbe90.png)

Is this a bug?

**Comment by sbs2001** [comment]
@uboznikov could you try running only a single small importer like `openssl`, via 
```
python manage.py import openssl
```

Just to confirm whether the  problem is with nvd importer.

**Comment by uboznikov** [comment]
@sbs2001 It's ok with OpenSSL, disk write throughput is very high while IO is very low, unlike with NVD.

![image](https://user-images.githubusercontent.com/16329085/108320122-5617d880-71fd-11eb-9d22-0b2aef2eb6ec.png)

![image](https://user-images.githubusercontent.com/16329085/108320282-8d868500-71fd-11eb-83ed-1a388c5ba85a.png)

**Comment by uboznikov** [comment]
I also tried importing GitHub only, got the following error:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/vulnerablecode/vulnerabilities/management/commands/import.py", line 77, in handle
    self.import_data(sources, options['cutoff_date'])
  File "/vulnerablecode/vulnerabilities/management/commands/import.py", line 99, in import_data
    self._import_data(importers, cutoff_date)
  File "/vulnerablecode/vulnerabilities/management/commands/import.py", line 105, in _import_data
    ImportRunner(importer, batch_size).run(cutoff_date=cutoff_date)
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 95, in run
    process_advisories(data_source)
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 121, in process_advisories
    advisory_batches = chain(data_source.updated_advisories(), data_source.added_advisories())
  File "/vulnerablecode/vulnerabilities/importers/github.py", line 110, in updated_advisories
    return self.batch_advisories(self.process_response())
  File "/vulnerablecode/vulnerabilities/importers/github.py", line 192, in process_response
    self.set_version_api(ecosystem)
  File "/vulnerablecode/vulnerabilities/importers/github.py", line 146, in set_version_api
    self.set_api(self.collect_packages(ecosystem))
  File "/vulnerablecode/vulnerabilities/importers/github.py", line 107, in set_api
    asyncio.run(self.version_api.load_api(packages))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/vulnerablecode/vulnerabilities/package_managers.py", line 306, in load_api
    await asyncio.gather(
  File "/vulnerablecode/vulnerabilities/package_managers.py", line 311, in fetch
    endpoint = self.composer_url(pkg)
  File "/vulnerablecode/vulnerabilities/package_managers.py", line 318, in composer_url
    vendor, name = pkg_name.split("/")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by sbs2001** [comment]
@uboznikov  thanks for pointing the github bug, I've pushed a fix.

As for the nvd, it's not a bug. That data source has huge data, so it makes tons of db queries, hence the disk activity. Recently we started collecting severity scores, that's probably increasing it further.

**Comment by uboznikov** [comment]
@sbs2001 Thanks for the quick fix, it's ok now.

I have put the import on a faster disk (RAID 0 Velociraptors), then restored the updated db in my laptop. It still took about 3+ hours on the faster disk. They're both on Ubuntu (LinuxLite 4.5 and Ubuntu 18.04, respectively).

I hope the NVD data import can be improved.

The other data import sources I have used doesn't suffer though from the disk hog.
