### ISSUE TITLE
Relation "vulnerabilities_importer" already exists

### ISSUE THREAD

**Issue by uboznikov** [nexB/vulnerablecode#366]
Hi there,

I have pulled from latest, then from https://github.com/nexB/vulnerablecode/issues/356 I tried to run both suggestions:

```
python manage.py makemigrations vulnerabilities
python manage.py migrate
```

```
python manage.py migrate --fake vulnerabilities zero
python manage.py migrate
```

But I'm getting the following error:

```
django.db.utils.ProgrammingError: relation "vulnerabilities_importer" already exists
```

At the moment is it still ok to use the codebase even with this error? Thanks.

**Comment by uboznikov** [comment]
I tried to run migrations:

```
DJANGO_DEV=1 python manage.py import github msr2019 kaybee npm
```

But I got:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 125, in process_advisories
    vuln, vuln_created = _get_or_create_vulnerability(advisory)
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 237, in _get_or_create_vulnerability
    vuln, created = models.Vulnerability.objects.get_or_create(vulnerability_id=advisory.vulnerability_id)  # nopep8
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column vulnerabilities_vulnerability.vulnerability_id does not exist
LINE 1: SELECT "vulnerabilities_vulnerability"."id", "vulnerabilitie...
                                                     ^

Successfully imported data from github
Importing data from msr2019
Successfully imported data from msr2019
Importing data from kaybee
Successfully imported data from kaybee
Importing data from npm
Successfully imported data from npm
root@30746278d1b8:/vulnerablecode# 
```

Prints successful at the end but I got a bunch of errors which look like db-related.

**Comment by sbs2001** [comment]
@uboznikov  seems like my suggestion didn't work , I guess you'd have to start fro scratch. We will make sure the migrations are squashed and in the version control
