### ISSUE TITLE
Error while importing npm data

### ISSUE THREAD

**Issue by ashykhov** [nexB/vulnerablecode#503]
```
**docker-compose run web bash
export GH_TOKEN=dfwef...
python manage.py import rust npm**
```
and got an error like this for npm :

```
Importing data from rust
Successfully imported data from rust
Importing data from npm
Traceback (most recent call last):
  File "/vulnerablecode/vulnerabilities/management/commands/import.py", line 110, in _import_data
    ImportRunner(importer, batch_size).run(cutoff_date=cutoff_date)
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 89, in run
    process_advisories(data_source)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/vulnerablecode/vulnerabilities/import_runner.py", line 116, in process_advisories
    advisory_batches = chain(data_source.updated_advisories(), data_source.added_advisories())
  File "/vulnerablecode/vulnerabilities/importers/npm.py", line 61, in updated_advisories
    processed_data = self.process_file(f)
  File "/vulnerablecode/vulnerabilities/importers/npm.py", line 91, in process_file
    all_versions = self.versions.get(package_name, until=publish_date).valid_versions
  File "/vulnerablecode/vulnerabilities/package_managers.py", line 61, in get
    if until and version.release_date and version.release_date > until:
TypeError: can't compare offset-naive and offset-aware datetimes
Failure to import data from npm. Continuing...
CommandError: 1 failed!: npm
```
 
fixed for one timelocally by editing if statement(removing one condition that failing) in using
```
**apt-get install vim
vi package_managers.py**
```
im using VulnerableCode under windows now, with docker-compose

**Comment by sbs2001** [comment]
Fixed via https://github.com/nexB/vulnerablecode/commit/475bb960ffda897538b431b005d366d812be41e9
