### ISSUE TITLE
github import: https://repo.packagist.org/p/subrion/cms.json not found

### ISSUE THREAD

**Issue by list4nestor** [nexB/vulnerablecode#557]
When importing github, get https://repo.packagist.org/p/subrion/cms.json not found error:
```
$ python manage.py import github
Importing data from github
Traceback (most recent call last):
  File "/opt/vulnerablecode/vulnerabilities/management/commands/import.py", line 110, in _import_data
    ImportRunner(importer, batch_size).run(cutoff_date=cutoff_date)
  File "/opt/vulnerablecode/vulnerabilities/import_runner.py", line 89, in run
    process_advisories(data_source)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/vulnerablecode/vulnerabilities/import_runner.py", line 116, in process_advisories
    advisory_batches = chain(data_source.updated_advisories(), data_source.added_advisories())
  File "/opt/vulnerablecode/vulnerabilities/importers/github.py", line 178, in updated_advisories
    return self.batch_advisories(self.process_response())
  File "/opt/vulnerablecode/vulnerabilities/importers/github.py", line 258, in process_response
    self.set_version_api(ecosystem)
  File "/opt/vulnerablecode/vulnerabilities/importers/github.py", line 213, in set_version_api
    self.set_api(self.collect_packages(ecosystem))
  File "/opt/vulnerablecode/vulnerabilities/importers/github.py", line 175, in set_api
    asyncio.run(self.version_api.load_api(packages))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/vulnerablecode/vulnerabilities/package_managers.py", line 68, in load_api
    await asyncio.gather(
  File "/opt/vulnerablecode/vulnerabilities/package_managers.py", line 345, in fetch
    resp = await session.request(method="GET", url=endpoint)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 625, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://repo.packagist.org/p/subrion/cms.json')
Failure to import data from github. Continuing...
```

**Comment by pombredanne** [comment]
Thank you for the report!
