### ISSUE TITLE
docker-compose build: add error detection or more docs

### ISSUE THREAD

**Issue by armijnhemel** [nexB/vulnerablecode#573]
```
$ docker-compose build
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied
```

So it is likely that something on my system is not set up properly (like permissions). Cleaner error detection and an error message would be good.

**Comment by sbs2001** [comment]
@armijnhemel  I'm unable to reproduce this on my side. 

Also why is the python version 3.9 ? According to our dockerfile it should be 3.8. Did you make any changes ?

**Comment by sbs2001** [comment]
@armijnhemel  I'm unable to reproduce this on my side. 

Also why is the python version 3.9 ? According to our dockerfile it should be 3.8. Did you make any changes ?

**Comment by armijnhemel** [comment]
> @armijnhemel I'm unable to reproduce this on my side.
> 
> Also why is the python version 3.9 ? According to our dockerfile it should be 3.8. Did you make any changes ?

It is 3.9 because that is on my system. I followed these instructions:

```
git clone https://github.com/nexB/vulnerablecode.git && cd vulnerablecode
make envfile
docker-compose build
docker-compose up
```

So this is before the Docker image is even *built*. This is output from the host system.

**Comment by armijnhemel** [comment]
Just to clarify: this is *NOT* a technical issue. It is a documentation issue. Just a few lines of extra docs (about the need for docker and/or podman would prevent people coming in complaining ;-)
